del build.js

type lib\myjs\Directions.js >> build.js
type lib\myjs\Pool.js >> build.js 
type lib\myjs\Swipe.js >> build.js 
type lib\myjs\ArrayUtils.js >> build.js 
type lib\myjs\MyAsync.js >> build.js 
type lib\myjs\MyAsync.js >> build.js 
type lib\myphaser\SimpleButton.js >> build.js 
type lib\myphaser\ImageBuilder.js >> build.js 
type lib\myphaser\Slider.js >> build.js 
type lib\myphaser\Fps.js >> build.js 
type lib\myphaser\Slice9Texture.js >> build.js 
type js\AppConfig.js >> build.js 
type js\abstract\JewelType.js >> build.js 
type js\abstract\JewelModel.js >> build.js 
type js\abstract\JewelLevel.js >> build.js 
type js\assets\R.js >> build.js 
type js\assets\Locale.js >> build.js 
type js\ProfitSystem.js >> build.js 
type js\assets\AssetLoader.js >> build.js 
type js\database\Repository.js >> build.js 
type js\database\ScoreRepository.js >> build.js 
type js\sounds\Sound.js >> build.js 
type js\widgets\JewelButtonType.js >> build.js 
type js\widgets\JewelButton.js >> build.js 
type js\widgets\ButtonBuilder.js >> build.js 
type js\widgets\effects\Explosion.js >> build.js 
type js\widgets\effects\EffectManager.js >> build.js 
type js\widgets\popups\StartPopup.js >> build.js 
type js\widgets\popups\GameOverPopup.js >> build.js 
type js\widgets\popups\SettingsPopup.js >> build.js 
type js\widgets\popups\ScoreTablePopup.js >> build.js 
type js\widgets\popups\LanguageMenuItem.js >> build.js 
type js\widgets\popups\LanguagePopup.js >> build.js 
type js\widgets\VolumeSlider.js >> build.js 
type js\widgets\JewelGenerator.js >> build.js 
type js\widgets\CristmasJewelGenerator.js >> build.js 
type js\widgets\BejeweledGrid.js >> build.js 
type js\widgets\BejeweledPresenter.js >> build.js 
type js\States.js >> build.js 
type lib\myphaser\UiTextButton.js >> build.js 
type js\windows\boot\Preloader.js >> build.js 
type js\windows\boot\PreloaderImage.js >> build.js 
type js\windows\main\ScoreLogic.js >> build.js 
type js\windows\main\MainState.js >> build.js 
type js\PhaserConfig.js >> build.js 
type js\Application.js >> build.js 